const F=Formwork,$=id=>document.getElementById(id),names={plate:'樓板模板',beam:'梁模板',column:'柱模板',wall:'牆模板'};
let mode='plate',states=Object.fromEntries(Object.keys(names).map(k=>[k,F.defaults(k)])),last=null,sensIndex=0;
const n=(v,k=3)=>Number.isFinite(v)?v.toLocaleString('en-US',{maximumFractionDigits:k,minimumFractionDigits:k}):'—';
const spanLabel=(i)=>mode==='beam'?['側 L1','側 L2','底 L1','底 L2','底 L3'][i]:'L'+(i+1);
const field=(key,label,value,unit='',min=0,step='any',full=false)=>`<label class="${full?'full':''}">${label}${unit?' <span class="muted">'+unit+'</span>':''}<input aria-label="${label}" type="number" inputmode="decimal" data-key="${key}" value="${value}" min="${min}" step="${step}"></label>`;
const select=(key,label,value,options,full=true)=>`<label class="${full?'full':''}">${label}<select data-key="${key}">${options.map(([v,t])=>`<option value="${v}" ${String(v)===String(value)?'selected':''}>${t}</option>`).join('')}</select></label>`;
const group=(title,body,open=true)=>`<details ${open?'open':''}><summary>${title}</summary><div class="fields">${body}</div></details>`;
const badge=(r,inclusive=false)=>`<span class="badge ${r<1||(inclusive&&r===1)?'':'fail'}">${r<1||(inclusive&&r===1)?'OK':'NG'}</span>`;
function renderInputs(){const d=states[mode];let html='';
 if(mode==='plate'||mode==='beam'){const o=mode==='beam'?2:0;html+=group('間距快速調整',field(`m.${o}.L`,'模板跨距 L1',d.members[o].L,'m',.001)+field(`m.${o+1}.L`,'角材跨距 L2',d.members[o+1].L,'m',.001)+field(`m.${o+2}.L`,'貫材跨距 L3',d.members[o+2].L,'m',.001)+`<div class="link-indicator"><b>尺寸雙向連動</b><span>L2 ↔ Y　L3 ↔ X</span><small>m 自動換算 cm</small></div><p class="note full">L1 是角材配置間距；L2 是貫材配置間距；L3 是貫材上的支柱間距。下方材料欄位會同步更新。</p>`);}

 if(mode==='plate'||mode==='beam')html+=group('01 / 垂直載重',`${mode==='plate'?field('wd','靜載重 WD',d.wd,'tf/m²'):field('H','梁高 H',d.H,'m',.001)+field('rho','混凝土單位重 γ',d.rho,'kgf/m³',1)}${field('wi','衝擊載重 WI',d.wi,'tf/m²')}${field('wl','施工活載重 WL',d.wl,'tf/m²')}<p class="note full">${mode==='plate'?'WD 依原程式直接輸入，請包含計畫採用的靜載重。':'梁底 WD = γH/1000；側壓 p = γH。依原程式，梁高直接用於自重與側壓。'} WI 為加算載重，非衝擊係數。</p>`);
 else html+=group('01 / 混凝土側壓',field('H','澆置高度 H',d.H,'m',.001)+field('rho','混凝土單位重 γ',d.rho,'kgf/m³',1)+field('R','澆置速度 R',d.R,'m/hr')+field('T','混凝土溫度 T',d.T,'°C',-17.7)+select('pressure','側壓計算方式',d.pressure,[['normal','原程式：一般混凝土'],['scc','原程式：SCC／一次澆灌'],['hydro','靜水壓 γH（新增比較）'],['manual','自行指定側壓（新增）']])+(d.pressure==='manual'?field('manualP','指定側壓',d.manualP,'kgf/m²',1,'any',true):'')+'<p class="note full">一般混凝土原標示：「一次澆灌不大於 1.2m」。SCC 分段式依原碼保留，適用性請核對澆置計畫；可切換靜水壓比較。</p>');
 html+=group('02 / 構件尺寸與材料',`<div class="full note">斷面以 cm 輸入，h 為受彎方向高度；E、Fb、Fv 單位為 kgf/cm²。</div>`+d.members.map((m,i)=>`<details class="full" ${i===0?'open':''}><summary>${m.name} <span class="muted" id="span-label-${i}">${spanLabel(i)} = ${n(m.L,3)} m</span></summary><div class="fields">${field(`m.${i}.L`,'跨距 '+spanLabel(i),m.L,'m',.001)}${select(`m.${i}.sim`,'支承模型',m.sim,[[1,'簡支'],[0,'原連續係數（非通用解）']],false)}${i===(mode==='beam'?2:0)||mode==='beam'&&i===0?field(`m.${i}.h`,'模板厚度 h',m.h,'cm',.001)+`<p class="note">計算條帶寬<br>${m.b} cm（固定）</p>`:select(`m.${i}.shape`,'斷面輸入',m.shape,[['rect','矩形 b × h'],['custom','自行指定 A、I、Z']])+(m.shape==='rect'?field(`m.${i}.b`,'寬度 b',m.b,'cm',.001)+field(`m.${i}.h`,'高度 h',m.h,'cm',.001):field(`m.${i}.A`,'斷面積 A',m.A,'cm²',.001)+field(`m.${i}.I`,'慣性矩 I',m.I,'cm⁴',.001)+field(`m.${i}.Z`,'斷面模數 Z',m.Z,'cm³',.001))}${field(`m.${i}.E`,'彈性係數 E',m.E,'',1)}${field(`m.${i}.Fb`,'容許彎曲應力 Fb',m.Fb,'',.001)}${field(`m.${i}.Fv`,'容許剪應力 Fv',m.Fv,'',.001)}<div class="props full" id="props-${i}"></div></div></details>`).join(''));
 if(mode==='plate'||mode==='beam')html+=group('03 / 垂直支撐',field('X','支撐分攤寬 X',d.X,'cm',.001)+field('Y','支撐分攤長 Y',d.Y,'cm',.001)+select('support','支撐種類',d.support,[['tube','鋼管支柱'],...(mode==='plate'?[['wood','木支柱']]:[]),['frame','重型鋼架／指定容量']])+(d.support==='tube'?field('D','鋼管外徑 D',d.D,'cm',.001)+field('t','壁厚 t',d.t,'cm',.001)+field('Lb','無側撐長 Lb',d.Lb,'cm',.001)+'<p class="note">原程式固定 K = 1<br>E = 2,100,000<br>Fy = 2,500 kgf/cm²</p>':d.support==='wood'?field('sw','木柱寬 b',d.sw,'cm',.001)+field('sh','木柱高 h',d.sh,'cm',.001)+field('Lb','無側撐長 Lb',d.Lb,'cm',.001)+field('Fc','基準容許壓應力',d.Fc,'kgf/cm²',.001):field('capacity','容許承載力',d.capacity,'tf',.001,'any',true)+'<p class="callout full">原程式固定 32 tf；此處可修改。請輸入所用產品及搭設條件的容許值。</p>')+'<p class="note full">X ↔ 貫材跨距 L3 × 100；Y ↔ 角材跨距 L2 × 100（m 換算 cm）。兩側皆可修改並同步重算。原計算不另加材料自重，亦未含斜撐、接頭、地基承壓與整體穩定檢核。</p>');
 if(mode!=='plate')html+=group('緊結器 / 拉力檢核',field('tieSp','緊結器間距 S',d.tieSp,'m',.001)+field('tieCapacity','每組容許拉力 Ta',d.tieCapacity,'kgf',.001)+`<p class="note full">預設容許值來源：${mode==='wall'?'螺栓桿 2.5 分，548':'螺栓桿 4 分，1433'} kgf。此為已折減的容許力；使用其他產品時直接修改。${mode==='beam'?'':'依原報表同時列出 T 與 2T。'}</p>`);
 html+=group('撓度判定',select('def','容許撓度',d.def,[['both','min(0.3 cm, L/240)'],['absolute','0.3 cm'],['relative','L/240']]),false);$('inputs').innerHTML=html;
 $('inputs').querySelectorAll('input,select').forEach(el=>el.addEventListener(el.tagName==='SELECT'?'change':'input',()=>{const key=el.dataset.key,keys=key.split('.'),v=el.type==='number'?(el.value===''?NaN:Number(el.value)):key.endsWith('.sim')?Number(el.value):el.value;F.setInput(d,key,v);syncDimensions(el);if(el.tagName==='SELECT'){const open=Array.from($('inputs').querySelectorAll('details')).map(x=>x.open);renderInputs();$('inputs').querySelectorAll('details').forEach((x,i)=>x.open=open[i]??true)}update();}));
}
function syncDimensions(active){
 const d=states[mode];
 d.members.forEach((m,i)=>{const label=$('span-label-'+i);if(label)label.textContent=`${spanLabel(i)} = ${n(m.L,3)} m`;});
 for(const el of $('inputs').querySelectorAll('input[data-key]')){
  const key=el.dataset.key;if(el===active||!(key==='X'||key==='Y'||/^m\.\d+\.L$/.test(key)))continue;
  const value=key==='X'||key==='Y'?d[key]:d.members[Number(key.split('.')[1])].L;
  el.value=Number.isFinite(value)?value:'';
 }
}
function utilization(r){return `<div class="util"><i class="${r>=1?'fail':''}" style="width:${Math.max(0,Math.min(100,r*100))}%"></i></div>`}
function cell(value,limit,ratio,dec=2){return `<td class="${ratio>=1?'cell-fail':''}">${n(value,dec)} <small>/ ${n(limit,dec)}</small></td>`;}
function resultTable(r){return `<div class="table-wrap"><table><thead><tr><th>構件 / 跨距</th><th>彎曲 fb / Fb<br>kgf/cm²</th><th>剪應力 fv / Fv<br>kgf/cm²</th><th>撓度 δ / 容許<br>cm</th><th>最大承載比</th><th>判定</th></tr></thead><tbody>${r.rows.map(x=>`<tr><td><b>${x.name}</b><small>${n(x.L,2)} m · ${x.sim?'簡支':'連續'}</small></td>${cell(x.fb,x.Fb,x.ratios[0])}${cell(x.fv,x.Fv,x.ratios[1])}${cell(x.delta,x.limit,x.ratios[2],4)}<td>${n(x.ratio,2)}${utilization(x.ratio)}</td><td>${badge(x.ratio)}</td></tr>`).join('')}</tbody></table></div>`;}
const diagramImages={plate:'images/plate.png',column:'images/column.png',wall:'images/wall.png',beam:'images/beam.png'};
function diagram(r){
 const d=states[mode],vertical=mode==='plate'||mode==='beam';
 return `<section class="schematic reference-diagram"><h2>${names[mode]} · 構件與跨距圖示</h2><figure><img src="${diagramImages[mode]}" alt="${names[mode]}構造圖，標示模板、角材、貫材與跨距 L1、L2、L3"><figcaption>依提供圖示呈現；圖形比例固定，下方尺寸隨輸入即時更新。</figcaption></figure><div class="dimension-values">${r.rows.map((m,i)=>`<span>${m.name} ${spanLabel(i)} <b>${n(m.L,3)} m</b></span>`).join('')}</div>${vertical?`<div class="dimension-values support-dimensions"><span>支撐分攤寬（L3）<b>X = ${n(d.X,1)} cm</b></span><span>支撐分攤長（L2）<b>Y = ${n(d.Y,1)} cm</b></span><span>分攤面積 X × Y <b>${n(d.X*d.Y/10000,3)} m²</b></span></div>`:`<p>側壓 p = ${n(r.p,1)} kgf/m²</p>`}</section>`;
}
function supportHTML(r){const d=states[mode];let h='';if(r.s){let s=r.s;h+=`<section class="panel"><div class="section-head"><h2>垂直支撐承載力</h2>${badge(s.ratio,d.support==='wood')}</div><div class="comparison"><span>需求 P <b>${n(s.P/1000)} tf</b></span><span>容許 Pa <b>${n(s.capacity/1000)} tf</b></span><span>承載比 <b>${n(s.ratio)}</b></span></div><p class="note">P = qXY/10 = ${n(r.q)} × ${n(d.X,1)} × ${n(d.Y,1)} / 10 = ${n(s.P)} kgf</p>${d.support==='frame'?'<div class="callout">指定容許承載力須對應實際支架型號、搭設高度與側向拘束；32 tf 僅為原程式預設。</div>':`<p class="note">A = ${n(s.A)} cm²　I = ${n(s.I)} cm⁴　r = ${n(s.r)} cm<br>λ = Lb/r = ${n(s.lambda)}${s.Cc?'　Cc = '+n(s.Cc):''}　Fa = ${n(s.Fa)} kgf/cm²</p>`}</section>`;}
 if(r.tie){let t=r.tie;h+=`<section class="panel"><div class="section-head"><h2>緊結器拉力</h2><span class="muted">每組容許 ${n(t.capacity,0)} kgf</span></div><div class="table-wrap"><table><thead><tr><th>檢核</th><th>需求 kgf</th><th>承載比</th><th>結果</th></tr></thead><tbody><tr><td>原式 T = p × S × ${mode==='beam'?'L側模板':'L直材'} / 2</td><td>${n(t.force,1)}</td><td>${n(t.ratio)}</td><td>${badge(t.ratio)}</td></tr>${mode!=='beam'?`<tr><td>原報表另列 2T</td><td>${n(t.doubleForce,1)}</td><td>${n(t.doubleRatio)}</td><td>${badge(t.doubleRatio)}</td></tr>`:''}</tbody></table></div><p class="note">原式分攤面積 = ${n(t.area,4)} m²。${mode!=='beam'?'原碼對 2T 未註明配置適用條件；本版保留獨立檢核，總覽納入較不利的 2T。':''}</p></section>`;}return h;}
function detailsHTML(r){return r.rows.map(x=>`<details class="detail-row"><summary>${x.name} · 斷面、內力與計算過程</summary><p>A = ${n(x.A)} cm²；I = ${n(x.I)} cm⁴；Z = ${n(x.Z)} cm³</p><p>E = ${n(x.E,0)} kgf/cm²；w = ${n(x.w,4)} kgf/cm；L = ${n(x.L*100,2)} cm</p><div class="formula">M = wL²/${x.sim?8:10} = ${n(x.M)} kgf·cm<br>V = wL/2 = ${n(x.V)} kgf<br>fb = M/Z = ${n(x.fb)} kgf/cm²<br>fv = 1.5V/A = ${n(x.fv)} kgf/cm²<br>δ = ${x.sim?'5wL⁴/(384EI)':'wL⁴/(128EI)'} = ${n(x.delta,5)} cm<br>δa = ${states[mode].def==='both'?'min(0.3, L/240)':states[mode].def==='absolute'?'0.3':'L/240'} = ${n(x.limit,5)} cm</div></details>`).join('');}
function sourceHTML(){const d=states[mode];return `<p>主要來源：附件 FormworkAnalysis_01/FormMain.vb 的 _CALCULATE_ENGINE_GO 與 _DMIN；初始參數取自 FormPlate、FormBeam、FormColumn、FormWall 的 _SETDEFAULT。此為附件算法重現，未宣稱已依現行規範重新校訂。</p><div class="formula">矩形斷面 A = bh；I = bh³/12；Z = bh²/6<br>簡支：M = wL²/8；δ = 5wL⁴/(384EI)<br>連續：M = wL²/10；δ = wL⁴/(128EI)<br>兩種模型均保留原式 V = wL/2、fv = 1.5V/A</div><p>連續梁使用原程式係數，並非任意跨數、跨比或載重配置的通用連續梁解。自訂斷面仍保留原式剪應力係數 1.5，未另算腹板剪應力。</p><h3>載重與傳遞</h3><p>樓板：q = WD + WI + WL（tf/m²），模板採 100 cm 寬，w模板 = 10q；w角材 = 10qL模板；w貫材 = 10qL角材。梁底模板改採 1 cm 寬，w底板 = q/10，梁底 q = γH/1000 + WI + WL。梁側 p = γH；柱牆側模板亦採 1 cm 寬，w模板 = p/10000，w直材 = pL模板/100，w橫材 = pL直材/100。此處傳遞式 L 單位為 m。</p><h3>柱、牆側壓（kgf/m²）</h3><div class="formula">柱：p₀ = 732 + 80100R/(T+17.8)，上限 14646<br>牆 R &lt; 2.1：p₀ 同柱，上限 9764<br>牆 R ≥ 2.1：p₀ = 732 + 117710/(T+17.8) + 24920R/(T+17.8)，上限 9764<br>p = min(max(min(p₀, 上限), 2929), γH) × γ/2403</div><p>上述 γ/2403 乘算次序照錄原碼。SCC 分段式亦照錄；牆在 H = 3m、4m 等邊界存在不連續，未擅自平滑或修正。可用新增的「靜水壓 γH」或「指定側壓」比較。</p><details><summary>SCC 分段式完整對照</summary><div class="formula">柱 R &lt; 10：H &lt; 1.5 時 p=γH，否則 p=γ[1.5+0.6(H−1.5)]<br>柱 10 ≤ R ≤ 20：H &lt; 2 時 p=γH，否則 p=γ[2+0.8(H−2)]<br>牆 R &lt; 10：H &lt; 1.5 時 p=γH；1.5 ≤ H &lt; 3 時 p=γ[1.5+0.2(H−1.5)]；3 ≤ H &lt; 4 時 p=1.5γ；H ≥ 4 時 p=γH<br>牆 10 ≤ R ≤ 20：H &lt; 2 時 p=γH；2 ≤ H &lt; 3 時 p=γ[2+0.4(H−2)]；3 ≤ H &lt; 4 時 p=2γ；H ≥ 4 時 p=γH<br>柱、牆 R &gt; 20：p=γH（H：m，R：m/hr）</div></details><h3>支柱算法</h3><div class="formula">鋼管 di = D−2t；A = π(D²−di²)/4；I = π(D⁴−di⁴)/64<br>r = √(I/A)；λ = Lb/r；Cc = √(2π²E/Fy)<br>λ &gt; Cc：Fa = 12π²E/(23λ²)<br>λ ≤ Cc：m = λ/Cc，Fa = (1−0.5m²)Fy/(5/3+3m/8−m³/8)<br>Pa = FaA；原程式 K=1，E=2100000，Fy=2500 kgf/cm²<br>木柱：r 採弱軸，Fa = kFc；λ ≤ 30 時 k=1；30 &lt; λ ≤ 100 時 k=1.3−0.01λ；λ &gt; 100 時 k=3000/λ²</div><p>原碼鋼柱彈性／非彈性分支的中文註解相反，本版以公式與 λ 分界呈現。木柱原輸入欄稱 Fb，此處依其軸壓用途標成「基準容許壓應力」。</p><h3>移植範圍與差異</h3><ul><li>完成四類模板的主要構件、支柱及緊結器檢核；不移植舊 Windows 檔案格式、材料資料庫與柱牆上中段間距建議功能。</li><li>矩形自動計算 A、I、Z；非矩形可自行輸入斷面性質。原模板條帶寬保留，所以樓板與梁模板的 M、V 數值不可直接跨類別比較。</li><li>原強度與撓度採嚴格小於；等於容許值判 NG。木柱沿用原式 P ≤ Pa。</li><li>以 JavaScript 雙精度計算；原碼採 Single，末位小數可能有差異。結果表採完整精度判定。</li><li>原程式固定 32 tf 支架改為可輸入；樓板及梁底 X 與 L3、Y 與 L2 雙向連動（X、Y 為 cm，L 為 m）；跨距敏感度為新增單構件比較，固定原構件線載重，未回算其他構件。</li><li>柱牆 2T 納入本版總覽；原程式主要 Ti_pass 只依 T 判定。所有 OK 僅代表已列出的計算項目。</li></ul>`;}
function update(){const d=states[mode],r=F.calculate(d);last=r;if(typeof refreshWorkbench==='function')refreshWorkbench();syncDimensions(document.activeElement);d.members.forEach((m,i)=>{const s=F.section(m),e=$('props-'+i);if(e)e.textContent=`A ${n(s.A,2)} cm² · I ${n(s.I,2)} cm⁴ · Z ${n(s.Z,2)} cm³`;});
 if(r.errors.length){$('result').innerHTML=`<div class="panel error" role="alert"><h2>請修正輸入參數</h2><ul>${r.errors.map(e=>`<li>${e}</li>`).join('')}</ul><p>參數完整前不顯示檢核結果。</p></div>`;$('sensitivity').innerHTML='參數修正後恢復試算。';$('calculation-details').innerHTML='請先修正參數。';$('print').disabled=true;$('word').disabled=true;return;}$('print').disabled=false;$('word').disabled=false;$('word').textContent='匯出'+names[mode].replace('模板','')+' Word';
 const load=mode==='plate'||mode==='beam'?r.q:r.p/1000,which=mode==='plate'||mode==='beam'?'總垂直載重 q':'混凝土側壓 p';
 $('result').innerHTML=`<section class="panel status ${r.pass?'':'fail'}" aria-live="polite"><div><h2>${r.pass?'已列數值檢核通過 · 適用性待確認':'有項目超出容許值'}</h2><div class="issue-tags">${r.rows.flatMap(x=>x.ratios.map((v,i)=>v>=1?`<span>${x.name} · ${['彎曲','剪力','撓度'][i]}</span>`:'')).join('')}${r.s&&!r.s.pass?'<span>垂直支撐 · 軸力</span>':''}${r.tie&&(r.tie.ratio>=1||(mode!=='beam'&&r.tie.doubleRatio>=1))?'<span>緊結器 · 拉力</span>':''}</div><p>${names[mode]} · ${r.rows.length} 組構件${r.s?'＋垂直支撐':''}${r.tie?'＋緊結器':''}</p></div><span class="badge ${r.pass?'':'fail'}">${r.pass?'OK':'需調整'}</span></section><div class="cards"><div class="card"><small>${which}</small><strong>${n(load,3)}</strong><span class="unit">tf/m²</span><em>${mode==='plate'?'WD + WI + WL':mode==='beam'?'γH/1000 + WI + WL':'依選定側壓公式'}</em></div><div class="card"><small>最大需求／容許比</small><strong class="${r.max>=1?'cell-fail':''}">${n(r.max,2)}</strong><span class="unit">倍</span><em>含已列支撐及拉力檢核</em></div><div class="card"><small>${r.s?'單支柱需求軸力':'緊結器需求拉力 T'}</small><strong>${n((r.s?r.s.P:r.tie.force)/1000,3)}</strong><span class="unit">tf</span><em>${r.s?'依 X × Y 分攤面積':'原式含 1/2 分攤係數'}</em></div></div><p class="scope-strip">目前為原程式算法檢核；模型、材料與整體穩定適用性請見「驗算與依據」。</p>${diagram(r)}<section class="panel"><div class="section-head"><h2>構件檢核總覽</h2><span class="muted">計算值 / 容許值</span></div>${resultTable(r)}<p class="note">承載比 ≥ 1 為 NG；紅字表示超限項目。原預設值亦完整呈現，不自動調整為合格。</p></section>${supportHTML(r)}`;
 $('calculation-details').innerHTML=`<div class="section-head"><h2>逐項計算過程</h2><span class="muted">Word 將自動包含完整公式與代入值</span></div>${detailsHTML(r)}`;
 $('source').innerHTML=sourceHTML();sensitivity();
}
function resetSensitivity(){sensIndex=Math.min(sensIndex,states[mode].members.length-1);$('sensMember').innerHTML=states[mode].members.map((m,i)=>`<option value="${i}">${m.name}</option>`).join('');$('sensMember').value=sensIndex;$('slider').value=Math.min(5,Math.max(.1,Math.round(states[mode].members[sensIndex].L/.05)*.05));sensitivity();}
function sensitivity(){if(!last||last.errors.length)return;const original=last.rows[sensIndex],L=+$('slider').value,trial=F.analyzeMember({...original,L},original.w,states[mode].def);$('sensL').textContent=n(L,2)+' m';const xMin=.1,xMax=5,at=l=>F.analyzeMember({...original,L:l},original.w,states[mode].def),yMax=Math.max(at(5).delta,at(5).limit)*1.08,x=l=>50+(l-xMin)/(xMax-xMin)*580,y=v=>178-v/yMax*145,path=Array.from({length:99},(_,i)=>{let l=.1+i*.05;return `${i?'L':'M'}${x(l)},${y(at(l).delta)}`}).join(' '),lim=Array.from({length:99},(_,i)=>{let l=.1+i*.05;return `${i?'L':'M'}${x(l)},${y(at(l).limit)}`}).join(' ');$('sensitivity').innerHTML=`<div class="chart"><svg viewBox="0 0 680 215" role="img" aria-label="跨距與撓度曲線，實線為撓度，虛線為容許撓度"><path d="M50 25V178H640" stroke="#c9d7e0" fill="none"/>${[0,.5,1].map(f=>`<path d="M50 ${y(yMax*f)}H640" stroke="#e9eff3"/><text x="4" y="${y(yMax*f)+4}">${n(yMax*f,1)}</text>`).join('')}<text x="4" y="16">δ (cm)</text><path d="${lim}" stroke="#b53937" stroke-dasharray="5 4" fill="none"/><path d="${path}" stroke="#087d87" stroke-width="2.5" fill="none"/><circle cx="${x(L)}" cy="${y(trial.delta)}" r="5" fill="#087d87"/><circle cx="${x(Math.min(5,Math.max(.1,original.L)))}" cy="${y(original.delta)}" r="4" fill="#164c78"/>${[.1,1,2,3,4,5].map(a=>`<text x="${x(a)-10}" y="199">${a}</text>`).join('')}<text x="638" y="199">L(m)</text><text x="360" y="22">實線：撓度　虛線：容許值</text></svg></div><div class="comparison"><span>原設計 <b>${n(original.L,2)} m</b><br>δ = ${n(original.delta,4)} cm</span><span>試算 <b>${n(L,2)} m</b><br>δ = ${n(trial.delta,4)} cm ${badge(trial.ratios[2])}</span><span>撓度變化<br><b>${original.delta>0?n(trial.delta/original.delta,2)+' 倍':'零載重'}</b></span></div><p class="note">拉霸 0.10–5.00 m，每格 0.05 m。固定此構件 w、E、I 與支承模型；藍點代表原設計，綠點代表試算。${original.L<.1||original.L>5?'原跨距超出圖表範圍，藍點置於邊界。':''}試算不套用回原參數。</p>`;}
$('modes').querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>{mode=btn.dataset.mode;sensIndex=0;$('modes').querySelectorAll('button').forEach(b=>{b.classList.toggle('active',b===btn);b.setAttribute('aria-pressed',b===btn?'true':'false')});renderInputs();update();resetSensitivity();}));
$('reset').onclick=()=>{states[mode]=F.defaults(mode);renderInputs();update();resetSensitivity();};$('sensMember').onchange=()=>{sensIndex=+$('sensMember').value;resetSensitivity();};$('slider').oninput=sensitivity;$('sensReset').onclick=resetSensitivity;
$('print').onclick=()=>{if(!last||last.errors.length)return;const d=states[mode],r=last;const params=Object.entries(d).filter(([k,v])=>typeof v!=='object'&&!['confirmed'].includes(k));const labels={mode:'類型',wd:'靜載重 WD (tf/m²)',wi:'衝擊 WI (tf/m²)',wl:'活載重 WL (tf/m²)',rho:'γ (kgf/m³)',H:'H (m)',R:'R (m/hr)',T:'T (°C)',pressure:'側壓方式',manualP:'指定側壓 (kgf/m²)',def:'撓度條件',X:'X (cm)',Y:'Y (cm)',Lb:'Lb (cm)',support:'支撐',D:'外徑 (cm)',t:'壁厚 (cm)',sw:'木柱 b (cm)',sh:'木柱 h (cm)',Fc:'木柱基準容許壓應力',capacity:'支架容量 (tf)',tieSp:'緊結器 S (m)',tieCapacity:'容許拉力 (kgf)'};
$('report').innerHTML=`<h1>${names[mode]}支撐計算書</h1><p>產生時間：${new Date().toLocaleString('zh-TW')}<br>資料依據：模板支撐計算(1).zip / FormMain.vb</p><h2>一、設計輸入</h2><p>以下保留本頁全部參數；未啟用的支撐、載重或側壓分支不參與運算。</p><table><tbody>${params.map(([k,v])=>`<tr><td>${labels[k]||k}</td><td>${v}</td></tr>`).join('')}</tbody></table><h2>二、構件資料</h2><table><thead><tr><th>構件</th><th>斷面 cm</th><th>L m</th><th>E</th><th>Fb</th><th>Fv</th></tr></thead><tbody>${d.members.map(m=>`<tr><td>${m.name}</td><td>${m.shape==='rect'?m.b+' × '+m.h:'A='+m.A+'; I='+m.I+'; Z='+m.Z}</td><td>${m.L}</td><td>${m.E}</td><td>${m.Fb}</td><td>${m.Fv}</td></tr>`).join('')}</tbody></table><h2>三、載重與檢核結果</h2><p>q = ${n(r.q,4)} tf/m²；p = ${n(r.p,2)} kgf/m²；最大承載比 = ${n(r.max,4)}；${r.pass?'已列項目通過':'有項目未通過'}</p>${resultTable(r)}${supportHTML(r)}<h2>四、詳細計算</h2>${detailsHTML(r)}<h2>五、公式與移植範圍</h2>${sourceHTML()}`;$('report').querySelectorAll('details').forEach(x=>x.open=true);window.print();};
renderInputs();update();resetSensitivity();
// Optional browser-standard structured read access to the visible calculation.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'read_formwork_analysis',title:'讀取模板支撐分析',description:'Read the currently visible formwork inputs, calculated checks, and validation errors without changing the design.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');return JSON.parse(JSON.stringify({mode,inputs:states[mode],results:F.calculate(states[mode])}));}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}

$('word').onclick=async()=>{const btn=$('word'),status=$('word-status');btn.disabled=true;status.textContent='正在產生 Word…';try{const data=FormworkWord.blocks(states[mode],F);const documentFile=FormworkWord.documentFromBlocks(data,docx);const blob=await docx.Packer.toBlob(documentFile);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=names[mode]+'詳細計算書_'+new Date().toLocaleDateString('sv-SE')+'.docx';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);status.textContent='Word 已產生';}catch(error){status.textContent='匯出失敗：'+error.message;}finally{btn.disabled=false;}};
